### ISSUE TITLE
Toggle Enchants causing crash on Forge 1.20.1

### ISSUE THREAD

**Issue by Gamemassa** [Dplayend/Toggle-Enchantments#1]
I'm not sure why, but Minecraft Forge 1.20.1 fails to launch when Toggle Enchantments is installed. I thought it might be a conflict with something else in my custom modpack so I tested Toggle Enchantments alone in a separate instance with no other mods and it still crashes when launching, so it's not a conflict.

**Comment by logixcraft** [comment]
I have the same issue

**Comment by Gantros** [comment]
same

**Comment by Gamemassa** [comment]
@Dplayend

**Comment by Dplayend** [comment]
sorry for being late, I was making the 1.12.2 of merge enchantments, today i will see the problem and fix it quickly, thanks for comments the issue, it help me a lot

**Comment by Dplayend** [comment]
fix it, I upload an older version. here is the correct jar
https://www.curseforge.com/minecraft/mc-mods/toggle-enchantments/files/4657182

**Comment by Gamemassa** [comment]
@Dplayend I just tested this and it's still not working.
